[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    authorization: для тестов авторизации
    registration: для тестов регистрации
    regression: для регрессионных тестов
    dashboard: для тестов, связанных с рабочей панелью
    courses: для тестов, связанных с курсами
