[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    authorization: для тестов авторизации пользователей
    registration: для тестов регистрации пользователей
    regression: для регрессионных тестов
    dashboard: для тестов, связанных с рабочей панелью
    courses: для тестов, связанных с курсами
