apps:
  - key: "ui-course"
    url: "https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/login"
    name: "UI Course"
    tags: [ "UI", "COURSES" ]
    repository: "https://github.com/Nikita-Filonov/qa-automation-engineer-ui-course"